version: 2
updates:
    # Maintain dependencies for GitHub Actions
    -   package-ecosystem: "github-actions"
        directory: "/"
        schedule:
            interval: "weekly"

    # Maintain dependencies for composer
    -   package-ecosystem: "composer"
        directory: "/"
        schedule:
            interval: "weekly"
        allow:
            # Allow both direct and indirect updates for all packages
            -   dependency-type: "all"


