version: '3.8'
services:
  php:
    env_file:
      - ./.docker.env
    container_name: "${PROJECT_NAME}${DOCKER_PHP_CONTAINER_NAME_SUFFIX}"
    build:
        context: ./.dev/docker/php
        dockerfile: Dockerfile.ci
    volumes:
      - .:/var/www/html
    ports:
      - "${DOCKER_PHP_PORT}:80"
    depends_on:
      - db-test
        
  db-test:
    container_name: "${PROJECT_NAME}_db-test"
    env_file:
      - ./.docker.env
    image: mysql:8.0
    working_dir: /application
    restart: on-failure
    command: [ mysqld, --character-set-server=utf8mb4, --innodb_flush_sync=0, --innodb_log_buffer_size=512M, --slow-query-log=0, --innodb_flush_log_at_trx_commit=0, --collation-server=utf8mb4_unicode_ci, --innodb_buffer_pool_size=512m --innodb-file-per-table=1, --lower_case_table_names=1 ]
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_TEST_DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_DB_TEST_DATABASE_USER}
      - MYSQL_USER=${DOCKER_DB_TEST_DATABASE_USER}
      - MYSQL_PASSWORD=${DOCKER_DB_TEST_DATABASE_PASSWORD}
    ports:
      - "${DOCKER_DB_TEST_PORT}:3306"
    tmpfs:
      - /var/lib/mysql
  

volumes:
    db: