version: '3.8'
services:
  php:
    env_file:
      - ./.docker.env
    container_name: "${PROJECT_NAME}${DOCKER_PHP_CONTAINER_NAME_SUFFIX}"
    build:
        context: ./.dev/docker/php
        dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.internal
      - DOCKER_PHP_APACHE_DOCUMENT_ROOT="${DOCKER_PHP_APACHE_DOCUMENT_ROOT}"
    ports:
      - "${DOCKER_PHP_PORT}:80"
    depends_on:
      - mailhog
      - db
      - db-test
      - redis
        
  mailhog:
    container_name: "${PROJECT_NAME}_mailhog"
    env_file:
      - ./.docker.env
    image: mailhog/mailhog
    ports:
      - "${DOCKER_MAILHOG_PORT}:8025"
  db:
    container_name: "${PROJECT_NAME}_db"
    env_file:
      - ./.docker.env
    image: mysql:8.0
    working_dir: /application
    restart: on-failure
    command: [ mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb-file-per-table=1, --lower_case_table_names=1 ]
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_DB_DATABASE_NAME}
      - MYSQL_USER=${DOCKER_DB_DATABASE_USER}
      - MYSQL_PASSWORD=${DOCKER_DB_DATABASE_PASSWORD}
    ports:
      - "${DOCKER_DB_PORT}:3306"

  db-test:
    container_name: "${PROJECT_NAME}_db-test"
    env_file:
      - ./.docker.env
    image: mysql:8.0
    working_dir: /application
    restart: on-failure
    command: [ mysqld, --character-set-server=utf8mb4, --innodb_flush_sync=0, --innodb_log_buffer_size=512M, --slow-query-log=0, --innodb_flush_log_at_trx_commit=0, --collation-server=utf8mb4_unicode_ci, --innodb_buffer_pool_size=512m --innodb-file-per-table=1, --lower_case_table_names=1 ]
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_TEST_DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DOCKER_DB_TEST_DATABASE_USER}
      - MYSQL_USER=${DOCKER_DB_TEST_DATABASE_USER}
      - MYSQL_PASSWORD=${DOCKER_DB_TEST_DATABASE_PASSWORD}
    ports:
      - "${DOCKER_DB_TEST_PORT}:3306"
    tmpfs:
      - /var/lib/mysql
        
  redis:
    image: redis:7
    container_name: "${PROJECT_NAME}_redis"
    restart: on-failure
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    volumes:
      - ./.dev/docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ redis-server, /usr/local/etc/redis/redis.conf ]

  redis-gui:
    image: redislabs/redisinsight:latest
    container_name: "${PROJECT_NAME}_redis_insight"
    restart: on-failure
    volumes:
      - redis_insight:/db
    ports:
      - "${DOCKER_REDIS_INSIGHT_PORT}:8001"
    links:
      - redis:redis
    depends_on:
      - redis

volumes:
    db:
    mailhog:
    redis_insight: