/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = {
  "/example/example": {
    post: {
      responses: {
        default: never;
      };
    };
  };
  "/example/example/{exampleId}": {
    get: {
      parameters: {
        path: {
          exampleId: string;
        };
      };
      responses: {
        default: never;
      };
    };
  };
};

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
