services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    App\Example\Infrastructure\WebApi\Controller\:
        resource: '../../../src/Example/Infrastructure/WebApi/Controller'
        public: true
        tags: [ 'controller.service_arguments' ]